### ISSUE TITLE
Run without test parameter

### ISSUE THREAD

**Issue by agamm** [lucgagan/auto-playwright#11]
I'd like to run it like so:
```
import { auto } from "auto-playwright";


(async () => { 
  const browser = await chromium.launch({ headless: true }); 
  const context = await browser.newContext(); 
  const page = await context.newPage(); 
  // Navigate to a website 
  await page.goto('https://www.example.com'); 
  
   // `auto` can query data
  // In this case, the result is plain-text contents of the header
  const headerText = await auto("get the header text", { page});
  ....
``

is it possible?

**Comment by tmcneal** [comment]
@agamm Just a heads up that this repo was cloned from a project called ZeroStep (https://github.com/zerostep-ai/zerostep) without attribution, and much of the text in the README and initial blog post was plagiarized from the ZeroStep project homepage (https://zerostep.com/). I wrote a blog post with proof of what I'm claiming: https://zerostep.com/blog/launch-on-thursday-cloned-by-saturday/
