### ISSUE TITLE
Video about Auto Playwright

### ISSUE THREAD

**Issue by elie222** [lucgagan/auto-playwright#15]
Full overview of codebase on YouTube:
https://youtu.be/l4vZhqAgmjU

My take on the controversy:
https://twitter.com/elie2222/status/1725322784937566401

I think it's worth mentioning ZeroStep in the README as you did take inspiration from it and copied some of their code.

**Comment by lucgagan** [comment]
Thank you for sharing your perspective.

After reflecting on the situation and my response to it for a day, I realize that I need to revise my position.

The ZeroStep project significantly influenced the development of Auto Playwright. I now understand how my actions, particularly copying parts of their documentation and code verbatim, may have been inappropriate. Although I began with a fresh start, I extensively reviewed their code to grasp its functionality. While I still believe the structures of our codebases are distinct, I recognize that I referred to their work while conceptualizing auto-playwright and that it is essential to properly credit the original creators.

I extend my apologies to the original authors for the manner in which I led this discussion. As one of my initial forays into open-source projects, I neglected to fully embrace the open-source ethos by failing to adequately acknowledge those who laid the foundation for my work. I am committed to improving in this regard.

I am grateful to everyone who dedicated time to this matter and helped me shape a healthier perspective.

The `README.md` has been also updated to properly acknowledge the work of the ZeroStep project.

**Comment by lucgagan** [comment]
Thank you for sharing your perspective.

After reflecting on the situation and my response to it for a day, I realize that I need to revise my position.

The ZeroStep project significantly influenced the development of Auto Playwright. I now understand how my actions, particularly copying parts of their documentation and code verbatim, may have been inappropriate. Although I began with a fresh start, I extensively reviewed their code to grasp its functionality. While I still believe the structures of our codebases are distinct, I recognize that I referred to their work while conceptualizing auto-playwright and that it is essential to properly credit the original creators.

I extend my apologies to @tmcneal and the original authors for the manner in which I led this discussion. As one of my initial forays into open-source projects, I neglected to fully embrace the open-source ethos by failing to adequately acknowledge those who laid the foundation for my work. I am committed to improving in this regard.

I am grateful to everyone who dedicated time to this matter and helped me shape a healthier perspective.

The `README.md` has been also updated to properly acknowledge the work of the ZeroStep project.

**Comment by yyx990805** [comment]
What is interesting it wasn't that easy to copy `getContentQuads` for example, as it would require mimicing zerostep's API. I like how those project rely on relatively low latency in terms of natural-langauge-query-based. I have been designing similar API's like zerostep's `ai` function (or now projects inspired by it) and I truly believe that it's the future. 
    Another thing is that there's a lot of other things which can be "invented" (the truth is that most probably those tools came to minds of some smart people, but what is important is who released them first). 
    Also the fact is that the programmers will be getting lazier and lazier, they will be less competent and such a tools are the way to go, but guys, let's truly respect each other's first contributions, especially MIT or (A)GPL. 

I will be watching this closely, while sometimes I might even try to push those tools to the limit and we will see how it goes. :) Thanks @lucgagan for mentioning ZeroStep in inspiration, at least this quick reaction proves that we might be, to some extent, in healthy FOSS environment.
