### ISSUE TITLE
Faced issues with import

### ISSUE THREAD

**Issue by Raksav** [lucgagan/auto-playwright#4]
![Screenshot 2023-11-12 102213](https://github.com/lucgagan/auto-playwright/assets/18206257/da87790e-dbe3-470b-b91c-937b23e02022)

**Comment by lucgagan** [comment]
Thank you for reporting. Fixed!

**Comment by tmcneal** [comment]
@Raksav Just a heads up that this repo was cloned from a project called ZeroStep (https://github.com/zerostep-ai/zerostep) without attribution, and much of text in the README and initial blog post was plagiarized from the ZeroStep project homepage (https://zerostep.com/). I wrote a blog post with proof of what I'm claiming: https://zerostep.com/blog/launch-on-thursday-cloned-by-saturday/
