### ISSUE TITLE
Unexpected token 'export'playwright - 1.8.0 version error

### ISSUE THREAD

**Issue by BMayhew** [lucgagan/auto-playwright#5]
When testing with version `1.8.0` 

```
import { test, expect } from "@playwright/test";
import { auto } from "auto-playwright";

...
  // `auto` can assert the state of the website
  // In this case, the result is a boolean outcome
  
  // this is missing a comma at the end
  const searchInputHasHeaderText = await auto(`Is the contents of the search box equal to "${headerText}"?` { page, test });
  
  // this seems to correct the code
  const searchInputHasHeaderText = await auto(`Is the contents of the search box equal to "${headerText}"?`, { page, test });
...
``` 

Once this was corrected I am getting this error on the import statement for { auto } `Unexpected token 'export'playwright`
![image](https://github.com/lucgagan/auto-playwright/assets/2488972/efd50795-4c4e-4b00-81ae-ce41c7dea58d)

**Comment by lucgagan** [comment]
Fixed in https://github.com/lucgagan/auto-playwright/releases/tag/v1.8.1 Thank you!

**Comment by tmcneal** [comment]
@BMayhew Just a heads up that this repo was cloned from a project called ZeroStep (https://github.com/zerostep-ai/zerostep) without attribution, and much of text in the README and initial blog post was plagiarized from the ZeroStep project homepage (https://zerostep.com/).
