### ISSUE TITLE
model parameter appears to be ignored

### ISSUE THREAD

**Issue by tntexplosivesltd** [lucgagan/auto-playwright#9]
I was trying to get the model parameter working for me, as I do not have access to GPT 4. It appears like the model parameter is ignored, however:

![image](https://github.com/lucgagan/auto-playwright/assets/854016/a8af9e02-7043-4fc1-866b-56487abdbe3e)

```
test('Test Google using GPT', async({ page }) => {
  await page.goto('https://www.google.com/');
  await auto('Search for "something else"', { page, test }, {model: 'gpt-3.5-turbo-1106', debug: true});
});
```

Maybe it might be good to log the model parameter if debugging is turned on?

**Comment by tmcneal** [comment]
@tntexplosivesltd Just a heads up that this repo was cloned from a project called ZeroStep (https://github.com/zerostep-ai/zerostep) without attribution, and much of the text in the README and initial blog post was plagiarized from the ZeroStep project homepage (https://zerostep.com/). I wrote a blog post with proof of what I'm claiming: https://zerostep.com/blog/launch-on-thursday-cloned-by-saturday/
